import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import fetch from 'isomorphic-unfetch';
import { userInfo } from 'os';
import axios from 'axios';
import { TodoType } from '../../types/todo';
import { getTodosAPI } from 'lib/apis/todo';

const Home = ({ data }) => {
  console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}></div>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  try {
    const { data } = await getTodosAPI();
    // const result = await axios.get<TodoType[]>(
    //   'http://localhost:3000/api/todo',
    // );
    console.log(data);

    return { props: { data } };
  } catch (error) {
    console.error(error);
    return { props: {} };
  }
};
export default Home;
